name: Periodic Health Check

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes
  workflow_dispatch: # Allows manual triggering from the GitHub Actions UI

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
      - name: Make HTTP Request
        run: |
          curl -X POST curl -X POSThttps://up-status.onrender.com/api/health-check
